openapi: 3.0.0

info:
  version: 0.1.0
  title: Lexical.cloud API
  description: Queryable interface for the data curated by Lexical.cloud

tags:
  - name: docs 
    description: Lookup entries for documented cloud products
  - name: glossary
    description: Lookup glossary terms for cloud computing
  - name: taxonomy
    description: Lookup by taxonomy for the cloud (services, providers, domains, categories, features, labels)

paths:

  /docs/{serviceId}/{providerId}/{docId}:
    get:
      description: Returns a documented entry for a service and provider
      tags:
        - docs
      parameters:
        - name: serviceId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for the service being offered
        - name: providerId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for the provider of the service
        - name: docId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for the documented entry
      responses:
        '200':
          description: Successfully returned a doc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doc'

  /glossary/{termId}:
    get:
      description: Returns a glossary entry for a term
      tags:
        - glossary
      parameters:
        - name: termId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for term in glossary
      responses:
        '200':
          description: Successfully returned a glossary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Definition'

  /{taxonomyId}/{termId}:
    get:
      description: Returns entry for a term within a taxonomy
      tags:
        - taxonomy
      parameters:
        - name: taxonomyId 
          in: path
          required: true
          schema:
            type: string
            enum:
              - services
              - providers
              - domains
              - categories
              - features
              - labels
          description: Identifier for the taxonomy
        - name: termId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for term in the taxonomy
      responses:
        '200':
          description: Successfully returned a taxonomy term
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Term'

  /{taxonomyId}/{termId}/relations:
    get:
      description: Returns relations for a term within a taxonomy
      tags:
        - taxonomy
      parameters:
        - name: taxonomyId 
          in: path
          required: true
          schema:
            type: string
            enum:
              - services
              - providers
              - domains
              - categories
              - features
              - labels
          description: Identifier for the taxonomy
        - name: termId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for term in the taxonomy
      responses:
        '200':
          description: Successfully returned relations for taxonomy term
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relation'

  /{taxonomyId}/{termId}/docs:
    get:
      description: Returns documented entries for a taxonomy term
      tags:
        - taxonomy
      parameters:
        - name: taxonomyId 
          in: path
          required: true
          schema:
            type: string
            enum:
              - services
              - providers
              - domains
              - categories
              - features
              - labels
          description: Identifier for the taxonomy
        - name: termId 
          in: path
          required: true
          schema:
            type: string
          description: Identifier for term in the taxonomy
      responses:
        '200':
          description: Successfully returned documented entries for a taxonomy term
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doc'

components:

  schemas:

    Definition:
      allOf:
        - type: object
          properties:
            title:
              type: string
              description: Title for proper display purposes
            url:
              type: string
              description: Link to definition
            permalink:
              type: string
              description: Path to definition entry
          required:
            - title
            - permalink
        - $ref: '#/components/schemas/Taxonomy'

    Doc:
      allOf:
        - type: object
          properties:
            name:
              type: string
              description: Full name of entry
            permalink:
              type: string
              description: Path to entry
          required:
            - name
            - permalink
        - $ref: '#/components/schemas/Taxonomy'

    Taxonomy:
      type: object
      properties:
        services:
          type: array 
          items:
            type: string
          description: List of service identifiers
        providers:
          type: array 
          items:
            type: string
          description: List of provider identifiers
        domains:
          type: array 
          items:
            type: string
          description: List of domain identifiers
        categories:
          type: array 
          items:
            type: string
          description: List of category identifiers
        features:
          type: array 
          items:
            type: string
          description: List of feature identifiers
        labels:
          type: array 
          items:
            type: string
          description: List of label identifiers

    Relation:
      type: object
      properties:
        hierarchical:
          $ref: '#/components/schemas/Taxonomy'
          description: Relations by hierarchy of term
        instance:
          type: array 
          items:
            type: string
          description: Instances of documentated products for term
        intersection:
          $ref: '#/components/schemas/Taxonomy'
          description: Intersections with terms outside hierarchy

    Term:
      type: object
      properties:
        id:
          type: string
          description: Identifier of term
        definition:
          $ref: '#/components/schemas/Definition'
          description: Definition of term
        type:
          type: string
          description: Taxonomy for the term 
        name:
          type: string
          description: Name of term for common usage
        permalink:
          type: string
          description: Path to term entry
      required:
        - id
        - type
        - name
        - permalink

